### PR TITLE
Change $state.frozen to $state.raw

### PR DESCRIPTION
**Pull request by icheered**
The following breaking PR affects this repository: https://github.com/sveltejs/svelte/pull/12808. The fix is simple, just change `$state.frozen` to `$state.raw` :). @vincjo Can you look at this and merge?

### CODE REVIEW

**Comment by vincjo** [comment]
Thx a lot :) 
I make my best to publish tomorrow

**Comment by icheered** [comment]
Making a new NPM release would be great, I'm working on a new project with svelte 5 and the automated build keeps failing x)

**Comment by icheered** [comment]
@vincjo Quick reminder to publish if possible :) 
(All builds on our test server keep failing haha)

**Comment by vincjo** [comment]
Finally I was able to get a computer.
Just published: `2.0.0-runes.32`

**Pull request merged**
